Pim1/Models/ClienteModel.cs
namespace Pim1.Models
{
    public class ClienteModel
    {
        public int Id { get; set; }
        public string Nomecli { get; set; }
        public int Cnpj { get; set; }
        public int Cpf { get; set; }
        public string email { get; set; }
        public string tipo { get; set; }

    }
}

Pim1/Models/ErrorViewModel.cs
namespace Pim1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Pim1/Models/HomeModel.cs
namespace Pim1.Models
{
    public class HomeModel
    {
        public string Nome { get; set; }
        public string Email { get; set; }
    }
}

Pim1/Models/ProdutoModel.cs
using System.ComponentModel.DataAnnotations;

namespace Pim1.Models
{
    public class ProdutoModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o nome para identificação do produto")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Digite a data de cultivo")]
        [DataType(DataType.Date, ErrorMessage = "Formato de data inválido")]
        public string Data { get; set; }

        [Required(ErrorMessage = "Digite a quantidade")]
        public int? Quantidade { get; set; }

        [Required(ErrorMessage = "Digite o valor unitário")]
        public float? Valor { get; set; }

    }
}

Pim1/Models/UsuarioModel.cs
using Pim1.Enums;
using System.ComponentModel.DataAnnotations;

namespace Pim1.Models
{
    public class UsuarioModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o nome do usuário")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Digite o login do usuário")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Digite o nome do e-mail do usuario")]
        [EmailAddress(ErrorMessage = "O e-mail informado não é válido!")]
        public string Email { get; set; }

        public PerfilEnum Perfil { get; set; }

        [Required(ErrorMessage = "Digite a senha do usuário")]
        public string Senha { get; set; }

        public DateTime DataCadastro { get; set; }
        public DateTime? DataAtualizacao { get; set; }
    }
}

Pim1/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;

namespace Pim1.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar()
        {
            return View();
        }

        public IActionResult ApagarConfirmacao()
        {
            return View();
        }

    }
}

Pim1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Pim1.Models;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Pim1.Controllers
{
    public class HomeController : Controller
    {
       
        public IActionResult Index()
        {
            HomeModel home = new HomeModel();

            home.Nome = "Usuario";
            home.Email = "Usuario@gmail.com";

            return View(home);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pim1/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using Pim1.Models;
using Pim1.Repositorio;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Pim1.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoRepositorio _produtorepositorio;
        public ProdutoController(IProdutoRepositorio produtoRepositorio)
        {
            _produtorepositorio = produtoRepositorio;
        }
        public IActionResult Index()
        {
            List<ProdutoModel> produtos = _produtorepositorio.BuscarTodos();

            return View(produtos);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar(int Id)
        {
            ProdutoModel produto = _produtorepositorio.ListarPorId(Id);
            return View(produto);
        }

        public IActionResult ApagarConfirmacao(int Id)
        {
            ProdutoModel produto = _produtorepositorio.ListarPorId(Id);
            return View(produto);
        }

        public IActionResult Apagar(int Id)
        {
            try
            {
                bool apagado = _produtorepositorio.Apagar(Id);

                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Produto deletado com sucesso";
                }
                else
                {
                    TempData["MensagemSucesso"] = "Não foi possível deletar o produto :( ";
                }

                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possível apagar o produto! :( - detalhes:{erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Criar(ProdutoModel produto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _produtorepositorio.Adicionar(produto);
                    TempData["MensagemSucesso"] = "Produto cadastrado com sucesso";
                    return RedirectToAction("Index");
                }

                return View(produto);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Erro ao cadastrar produto! :( - detalhes:{erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Alterar(ProdutoModel produto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _produtorepositorio.Atualizar(produto);
                    TempData["MensagemSucesso"] = "Produto alterado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View("Editar", produto);
            }
            catch (Exception erro)
            {

                TempData["MensagemErro"] = $"Erro ao alterar produto! :( - detalhes:{erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

Pim1/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Pim1.Models;
using Pim1.Repositorio;

namespace Pim1.Controllers
{
    public class UsuarioController : Controller
    {

        private readonly IUsuarioRepositorio _usuariorepositorio;
        public UsuarioController(IUsuarioRepositorio usuarioRepositorio)
        {
            _usuariorepositorio = usuarioRepositorio;
        }
        public IActionResult Index()
        {
            List<UsuarioModel> usuarios = _usuariorepositorio.BuscarTodos();

            return View(usuarios);
        }
        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(UsuarioModel usuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _usuariorepositorio.Adicionar(usuario);
                    TempData["MensagemSucesso"] = "Usuário cadastrado com sucesso";
                    return RedirectToAction("Index");
                }

                return View(usuario);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Erro ao cadastrar usuário! :( - detalhes:{erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

Pim1/Views/Cliente/ApagarConfirmacao.cshtml
@{
    ViewData["Title"] = "Confirma&ccedil;&atilde;o de deletar cliente";
}

<div>
     <h3>Realmente deseja deletar o cliente?</h3>
</div>

<a class="btn btn-primary" role="button" asp-asp-controller="Cliente" asp-action="Apagar">Sim,deletar</a>
<a class="btn btn-danger" role="button" asp-controller="Cliente" asp-action="Index">N&atilde;o!</a>

Pim1/Views/Cliente/Criar.cshtml
@{
    ViewData["Title"] = "Criar Cliente";
}

<div class="text-center">

   
    <h1 class="display-4">Cadastrar teste Cliente</h1>

</div>

<form>

    <div class="form-group">
        <label for="nomecli">Nome</label>
        <input type="text" class="form-control" placeholder="Digite o nome do Cliente">
    </div>

    <br />

    <div class="form-group">
        <label for="cpf">CPF</label>
        <input type="text" class="form-control" placeholder="Digite o cpf do cliente">
    </div>

    <br />

    <div class="form-group">
        <label for="cnpj">CNPJ</label>
        <input type="text" class="form-control" placeholder="Digite o cnpj do cliente">
    </div>

    <br />

    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" placeholder="Digite o email do cliente">
    </div>

    <br />
    <div class="form-group">
        <label for="tipocliente">Tipo de cliente</label>
        <select class="form-control" id="tipocliente">
            <option value="">Selecione o tipo de cliente</option>
            <option value="pf">PF</option>
            <option value="pj">PJ</option>
        </select>
    </div>


    <br /> 
    <button type="submit" class="btn btn-primary">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="cliente" asp-action="Index" role="button">Voltar</a>
</form>

Pim1/Views/Cliente/Editar.cshtml
@{
    ViewData["Title"] = "Editar Cliente";
}

<div class="text-center">


    <h1 class="display-4">Editar Cliente</h1>

</div>

<form>

    <div class="form-group">
        <label for="nomecli">Nome</label>
        <input type="text" class="form-control" placeholder="Digite o nome do Cliente">
    </div>

    <br />

    <div class="form-group">
        <label for="cpf">CPF</label>
        <input type="text" class="form-control" placeholder="Digite o cpf do cliente">
    </div>

    <br />

    <div class="form-group">
        <label for="cnpj">CNPJ</label>
        <input type="text" class="form-control" placeholder="Digite o cnpj do cliente">
    </div>

    <br />

    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" placeholder="Digite o email do cliente">
    </div>

    <br />
    <div class="form-group">
        <label for="tipocliente">Tipo de cliente</label>
        <select class="form-control" id="tipocliente">
            <option value="">Selecione o tipo de cliente</option>
            <option value="pf">PF</option>
            <option value="pj">PJ</option>
        </select>
    </div>


    <br />
    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="cliente" asp-action="Index" role="button">Voltar</a>
</form>

Pim1/Views/Cliente/Index.cshtml
@{
    ViewData["Title"] = "Listagem de Clientes";
}
<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Cliente" asp-action="Criar" >Adicionar novo cliente</a>
    </div>

    <h1 class="display-4">Clientes</h1>

<br /><br />

<table class="table table-striped-columns">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nome</th>
            <th scope="col">CPF/CNPJ</th>
            <th scope="col">Email</th>
            <th scope="col">Tipo</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>Ronaldo Fenomeno</td>
            <td>1234</td>
            <td>ronaldo@brilhamuito.com</td>
            <td>PJ</td>
            <td>
                <div class="btn-group" role="group">
                    <a role="button" class="btn btn-primary" asp-controller="Cliente" asp-action="Editar">Editar</a>
                        <a role="button" class="btn btn-danger" asp-controller="Cliente" asp-action="ApagarConfirmacao">Deletar</a>
                </div>
            </td>
        </tr>
    </tbody>
</table>
</div>

Pim1/Views/Home/Index.cshtml
@model HomeModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo(a) @Model.Nome !</h1>
    <br /><br />

    <style>
        .texto-destaque {
            font-size: 27px; /* Altere para o tamanho desejado */
            font-weight: inherit; /* Pode ser 'normal', 'bold', ou um número como 700 */
        }
    </style>

    <p class="texto-destaque">Sistema Fazenda Urbana - PIM &copy;</p>
</div>

Pim1/Views/Produto/ApagarConfirmacao.cshtml
@model ProdutoModel
@{
    ViewData["Title"] = "Confirma&ccedil;&atilde;o de deletar produto";
}

<div>
     <h3>Realmente deseja deletar o produto (@Model.Nome)?</h3>
</div>

<a class="btn btn-primary" role="button" asp-asp-controller="Produto" asp-action="Apagar" asp-route-id="@Model.Id">Sim,deletar</a>
<a class="btn btn-danger" role="button" asp-controller="Produto" asp-action="Index">N&atilde;o!</a>

Pim1/Views/Produto/Criar.cshtml
@model ProdutoModel
@{
    ViewData["Title"] = "Criar Produto";
}

<div class="text-center">

   
    <h1 class="display-4">Cadastrar Produto</h1>

</div>

<form asp-controller="Produto" asp-action="Criar" method="post">

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome"  class="form-control" placeholder="Digite o nome do produto/alimento colhido">
           @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <br />

    <div class="form-group">
        <label for="data">Data da colheita</label>
        <input type="text" asp-for="Data" class="form-control" placeholder="Digite a data da colheita">
        @Html.ValidationMessageFor(x => x.Data)
    </div>

    <br />

    <div class="form-group">
        <label for="quantidade">Quantidade</label>
        <input type="text" asp-for="Quantidade" class="form-control" placeholder="Digite a quantidade colhida">
        @Html.ValidationMessageFor(x => x.Quantidade)
    </div>

    <br />

    <div class="form-group">
        <label for="valor">Valor Unit.</label>
        <input type="text" asp-for="Valor" class="form-control" placeholder="Digite o valor unit&aacute;rio do produto/alimento colhido">
        @Html.ValidationMessageFor(x => x.Valor)
    </div>

    <br /> 
    <button type="submit" class="btn btn-primary">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="produto" asp-action="Index" role="button">Voltar</a>
</form>

Pim1/Views/Produto/Editar.cshtml
@model ProdutoModel
@{
    ViewData["Title"] = "Editar Produto";
}

<div class="text-center">


    <h1 class="display-4">Editar Produto</h1>

</div>

<form asp-controller="Produto" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id"/>
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do produto/alimento colhido">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <br />

    <div class="form-group">
        <label for="data">Data da colheita</label>
        <input type="text" asp-for="Data" class="form-control" placeholder="Digite a data da colheita">
        @Html.ValidationMessageFor(x => x.Data)
    </div>

    <br />

    <div class="form-group">
        <label for="quantidade">Quantidade</label>
        <input type="text" asp-for="Quantidade" class="form-control" placeholder="Digite a quantidade colhida">
        @Html.ValidationMessageFor(x => x.Quantidade)
    </div>

    <br />

    <div class="form-group">
        <label for="valor">Valor Unit.</label>
        <input type="text" asp-for="Valor" class="form-control" placeholder="Digite o valor unit&aacute;rio do produto/alimento colhido">
        @Html.ValidationMessageFor(x => x.Valor)
    </div>

    <br />
    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="produto" asp-action="Index" role="button">Voltar</a>
</form>

Pim1/Views/Produto/Index.cshtml
@model List<ProdutoModel>
@{
    ViewData["Title"] = "Listagem de Produtos";
}
<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Produto" asp-action="Criar" >Adicionar novo produto</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    { 
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
    }

     @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
           @TempData["MensagemErro"]
        </div>
    }
    <br />
    <h1 class="display-4">Produtos Disponíveis</h1>

<br />

<table class="table table-striped-columns" id="table-produtos">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Produto</th>
            <th scope="col">Data de Entrada</th>
            <th scope="col">Quantidade Estoque</th>
            <th scope="col">Valor Unit.</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @if(Model != null && Model.Any())
        {
            foreach (ProdutoModel produto in Model)
            {
                    <tr>
                        <th scope="row">@produto.Id</th>
                        <td>@produto.Nome</td>
                        <td>@produto.Data</td>
                        <td>@produto.Quantidade</td>
                        <td>@produto.Valor</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@produto.Id" asp-controller="Produto" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@produto.Id"  asp-controller="Produto" asp-action="ApagarConfirmacao">Deletar</a>
                            </div>
                        </td>
                    </tr>
            }
        }
        else
        {
                <tr class="odd"><td valign="top" colspan="5">Nenhum Produto encontrado</td></tr>
        }
    </tbody>
</table>
</div>

Pim1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mirai System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pim1.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand"><img src="~/images/LogoMirai.png" height="80px" width="80px"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="font-size: 18px; font-weight: normal;"  asp-area="" asp-controller="Home" asp-action="Index">P&aacute;gina Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="font-size: 18px; font-weight: normal;" asp-area="" asp-controller="Usuario" asp-action="Index">Usuários</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="font-size: 18px; font-weight: normal;" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                       <li class="nav-item">
                            <a class="nav-link text-dark" style="font-size: 18px; font-weight: normal;" asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Mirai System PIM 2024 -  <a asp-area="" asp-controller="Home" asp-action="Privacy">UNIP</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.1.8/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pim1/Views/Usuario/Criar.cshtml
@using Pim1.Enums
@model UsuarioModel
@{
    ViewData["Title"] = "Criar Usuario";
}

<div class="text-center">

   
    <h1 class="display-4">Cadastrar Usuario</h1>

</div>

<form asp-controller="Usuario" asp-action="Criar" method="post">

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do usuário">
           @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <br />

    <div class="form-group">
        <label for="nome">Email</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o email do usuário">
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <br />

    <div class="form-group">
        <label for="nome">Login</label>
        <input type="text" asp-for="Login" class="form-control" placeholder="Digite o login do usuário">
        @Html.ValidationMessageFor(x => x.Login)
    </div>
    <br />
    <div class="form-group">
        <label for="nome">Perfil</label>
       <select asp-for="Perfil" class="form-control">
           <option value="0">Selecione</option>
           <option value="@PerfilEnum.Admin">Administrador</option>
           <option value="@PerfilEnum.Padrao">Padrão</option>
       </select>
    </div>
    <br />
    <div class="form-group">
        <label for="nome" class="form-label">Senha</label>
        <input type="password" asp-for="Senha" class="form-control" placeholder="Digite a senha do usuário">
        @Html.ValidationMessageFor(x => x.Senha)
    </div>


    <br /> 
    <button type="submit" class="btn btn-primary">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="produto" asp-action="Index" role="button">Voltar</a>
</form>

Pim1/Views/Usuario/Index.cshtml
@model List<UsuarioModel>
@{
    ViewData["Title"] = "Listagem de Usuarios";
}
<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Usuario" asp-action="Criar" >Adicionar novo Usuário</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    { 
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
    }

     @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
           @TempData["MensagemErro"]
        </div>
    }
    <br />
    <h1 class="display-4">Usuários cadastrados</h1>

<br />

<table class="table table-striped-columns" id="table-usuarios">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nome</th>
            <th scope="col">Login</th>
            <th scope="col">Email</th>
            <th scope="col">Data de Cadastro</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @if(Model != null && Model.Any())
        {
                foreach (UsuarioModel usuario in Model)
            {
                    <tr>
                        <th scope="row">@usuario.Id</th>
                        <td>@usuario.Nome</td>
                        <td>@usuario.Login</td>
                        <td>@usuario.Email</td>
                        <td>@usuario.DataCadastro</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@usuario.Id"  asp-controller="Usuario" asp-action="ApagarConfirmacao">Deletar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhum Usuário encontrado</td></tr>
            }
        </tbody>
</table>
</div>

Pim1/Views/Venda/ApagarConfirmacao.cshtml
@{
    ViewData["Title"] = "Confirma&ccedil;&atilde;o de deletar produto";
}

<div>
     <h3>Realmente deseja deletar o produto?</h3>
</div>

<a class="btn btn-primary" role="button" asp-asp-controller="Produto" asp-action="Apagar">Sim,deletar</a>
<a class="btn btn-danger" role="button" asp-controller="Produto" asp-action="Index">N&atilde;o!</a>

Pim1/Views/Venda/Index.cshtml
@{
    ViewData["Title"] = "Listagem de Vendas";
}
<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Venda" asp-action="Criar" >Registrar venda</a>
    </div>

    <h1 class="display-4">Vendas realizadas</h1>

<br /><br />

<table class="table table-striped-columns">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Data da venda</th>
            <th scope="col">Cliente</th>
            <th scope="col">Produto</th>
            <th scope="col">Quantidade vendida</th>
            <th scope="col">Valor Unit.</th>
            <th scope="col">Valor Total</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>21/21/2121</td>
            <td>Messi</td>
            <td>cenoura</td>
            <td>10</td>
            <td>5</td>
            <td>50</td>
            <td>
                <div class="btn-group" role="group">
                    <a role="button" class="btn btn-primary" asp-controller="Venda" asp-action="Editar">Editar</a>
                    <a role="button" class="btn btn-danger" asp-controller="Venda" asp-action="ApagarConfirmacao">Deletar</a>
                </div>
            </td>
        </tr>
        <tr>
            <th scope="row">1</th>
            <td>Tomate</td>
            <td>21/12/2024</td>
            <td>2</td>
            <td>R$ 10</td>
            <td>
                <div class="btn-group" role="group">
                    <a role="button" class="btn btn-primary" asp-controller="Produto" asp-action="Editar">Editar</a>
                    <a role="button" class="btn btn-danger" asp-controller="Produto" asp-action="ApagarConfirmacao">Deletar</a>
                </div>
            </td>
        </tr>
        <tr>
            <th scope="row">1</th>
            <td>Tomate</td>
            <td>21/12/2024</td>
            <td>2</td>
            <td>R$ 10</td>
            <td>
                <div class="btn-group" role="group">
                    <a role="button" class="btn btn-primary" asp-controller="Produto" asp-action="Editar">Editar</a>
                    <a role="button" class="btn btn-danger" asp-controller="Produto" asp-action="ApagarConfirmacao">Deletar</a>
                </div>
            </td>
        </tr>
    </tbody>
</table>
</div>